### ISSUE TITLE
Environment Setup

### ISSUE THREAD

**Issue by XUHUAKing** [epic-kitchens/epic-kitchens-100-hand-object-bboxes#12]
Hi, I tried to run the notebook, but when I call
`from epic_kitchens.hoa import load_detections, DetectionRenderer`

it gives the below error message in `types.py`, 
`import epic_kitchens.hoa.types_pb2 as pb`
`AttributeError: module 'epic_kitchens' has no attribute 'hoa'`

I am not sure whether I have missed something during the setup process. Thanks!

**Comment by willprice** [comment]
Did you run ` python setup.py install` in the root of this repo when you cloned it?

**Comment by XUHUAKing** [comment]
Yes, I have run it in the root. Do I need to change anything inside the setup.py before running it?

**Comment by willprice** [comment]
Nope, you shouldn't need to.
To debug it, can you add
`import sys; print(sys.executable); print(sys.path)` at the end of the imports in `setup.py`, run `python setup.py install` again and copy and paste the log here. 
Then can you try and run the notebook again, but this time, can you also add `import sys; print(sys.executable); print(sys.path)` in a new cell at the top and paste the output here.

**Comment by XUHUAKing** [comment]
Below attached the two logs per your request:

1. (in `setup.py`)
['/home/NAME/epic-kitchens-100-hand-object-bboxes', '/home/NAME/anaconda3/envs/ego/lib/python36.zip', '/home/NAME/anaconda3/envs/ego/lib/python3.6', '/home/NAME/anaconda3/envs/ego/lib/python3.6/lib-dynload', '/home/NAME/anaconda3/envs/ego/lib/python3.6/site-packages', '/home/NAME/anaconda3/envs/ego/lib/python3.6/site-packages/epic_hand_object_detections-0.0.1-py3.6.egg']

2. (in notebook)
['/home/NAME/epic-kitchens-100-hand-object-bboxes/notebooks', '/home/NAME/anaconda3/envs/ego/lib/python36.zip', '/home/NAME/anaconda3/envs/ego/lib/python3.6', '/home/NAME/anaconda3/envs/ego/lib/python3.6/lib-dynload', '/home/NAME/anaconda3/envs/ego/lib/python3.6/site-packages', '/home/NAME/anaconda3/envs/ego/lib/python3.6/site-packages/epic_hand_object_detections-0.0.1-py3.6.egg']
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    from epic_kitchens.hoa import load_detections, DetectionRenderer
  File "/home/NAME/anaconda3/envs/ego/lib/python3.6/site-packages/epic_hand_object_detections-0.0.1-py3.6.egg/epic_kitchens/hoa/__init__.py", line 1, in <module>
    from .io import load_detections, save_detections
  File "/home/NAME/anaconda3/envs/ego/lib/python3.6/site-packages/epic_hand_object_detections-0.0.1-py3.6.egg/epic_kitchens/hoa/io.py", line 6, in <module>
    from .types import FrameDetections
  File "/home/NAME/anaconda3/envs/ego/lib/python3.6/site-packages/epic_hand_object_detections-0.0.1-py3.6.egg/epic_kitchens/hoa/types.py", line 10, in <module>
    import epic_kitchens.hoa.types_pb2 as pb
AttributeError: module 'epic_kitchens' has no attribute 'hoa'

**Comment by XUHUAKing** [comment]
I fixed this issue by changing line 10 in `types.py` to `import .types_pb2 as pb`, it is some relative path issues. BTW, thanks for the great work and I will close this issue.
