### ISSUE TITLE
Content of .pkl files - understanding the automatic annotations

### ISSUE THREAD

**Issue by anjugopinath** [epic-kitchens/epic-kitchens-100-hand-object-bboxes#13]
Hi,

I downloaded the .pkl files in the below locations and loaded them using pandas.
https://data.bris.ac.uk/data/dataset/730b32a5da580422ba8833790f0eeef1 - Automatic Annotations/hand-objects/P01
![image](https://user-images.githubusercontent.com/4654298/128121522-a498e5b4-e8c6-46a9-a868-def71285a243.png)

And this one,
https://data.bris.ac.uk/data/dataset/9a7adc61299dfb608c110fc90c25518a - Automatic Annotations/masks/P01
![image](https://user-images.githubusercontent.com/4654298/128121648-2457c793-0789-4a83-8721-92e945718478.png)

I am not sure how to interpret these.

Thank You,
Anju

**Comment by willprice** [comment]
Hi there,
Have a look at https://github.com/epic-kitchens/epic-kitchens-100-hand-object-bboxes. You need to install the supporting library to load the files as they are pickled protobuf. There is a notebook in the repo demonstrating this.

Kind regards,
Will

**Comment by anjugopinath** [comment]
Got it working with the help of the jupyter notebook. Thank You!
