### ISSUE TITLE
Object and verb names

### ISSUE THREAD

**Issue by anjugopinath** [epic-kitchens/epic-kitchens-100-hand-object-bboxes#16]
Is it possible to get the object and verb names using the library?

Thank You

**Comment by willprice** [comment]
Hi,
No it isn't possible, the hand and object bounding boxes are not labelled with this information. You can find what annotations we do have at https://github.com/epic-kitchens/epic-kitchens-100-annotations

**Comment by anjugopinath** [comment]
Thank You. I hope this feature is added in the future. It would be very convenient when creating annotation (.pkl) files for training.
