### ISSUE TITLE
Segment id of frames

### ISSUE THREAD

**Issue by anjugopinath** [epic-kitchens/epic-kitchens-100-hand-object-bboxes#17]
Is it possible to get the segment number of the frame from this library?

I know one can get the participant id and video id (P01_01).
I would like to know if we can also get the segment id - say 111 (P01_01_111).

Thank You.

**Comment by dimadamen** [comment]
This is not possible because segments can be overlapping. The same frame can be part of multiple segments.
However all information to find all corresponding segments are available in the main annotations repo.
Please check the full set of repos and README before asking questions.
