### ISSUE TITLE
Run the library on new images

### ISSUE THREAD

**Issue by luohwu** [epic-kitchens/epic-kitchens-100-hand-object-bboxes#18]
Hi team,

I am wondering can this library be used for new images? The example notebook just loads results from .pkl file. And how can I apply the library to new images? I did not find such an example. Thanks in advance.

**Comment by willprice** [comment]
This library is simply for pre-extracted hand object detections. If you wish to extract new detections on different data, then please see https://github.com/ddshan/hand_object_detector (we used the handobj_100k+ego model)

**Comment by luohwu** [comment]
I see. Thanks a lot
