### ISSUE TITLE
Scaling and Isolating Hand annotations

### ISSUE THREAD

**Issue by Linardos** [epic-kitchens/epic-kitchens-100-hand-object-bboxes#3]
Greetings and many thanks for this great work. I am currently trying to figure out how to use the EPIC KITCHENS dataset in my project which is related to hand-motion. Towards that goal I need to crop and isolate the frames over the bounding boxes that detect hands. 

I ran the demo on an example from P01_01 and it seems that by default the bounding boxes are relatively small compared to what I want so I wanted to ask how I can scale and isolate the hand annotations (I don't care about the object). I noticed that there is a "scale" method on the FrameDetection class but I am not entirely sure how to use it.

Below you can see my naive attempt:

![image](https://user-images.githubusercontent.com/26694607/86822763-b4d87980-c094-11ea-914d-9e82895c99fa.png)

**Comment by dimadamen** [comment]
You might want to refer to the paper we use on detecting hands (Understanding Human Hands in Contact at Internet Scale - CVPR 2020). The paper only detects the palm until the wrist and no further. If you want to detect the full hand+arm, then our detections would not be suitable for your purposes.
