### ISSUE TITLE
Impact of erratum

### ISSUE THREAD

**Issue by escorciav** [epic-kitchens/epic-kitchens-100-hand-object-bboxes#4]
Dear dataset maintainers,

Could you please confirm if [this erratum](https://github.com/epic-kitchens/epic-kitchens-100-annotations/blob/master/README.md#erratum) impacts these detections?

If so, kindly advise how to proceed.

Thanks for such a cool dataset!

**Comment by willprice** [comment]
Hi Victor,

Good catch, I'm not sure we released updated versions of the detections (or masks) for these videos.

Here are the corrected files:

https://www.dropbox.com/s/fjvhpd4o9l2n08y/P01_109.pkl?dl=0
https://www.dropbox.com/s/ocvy4fskv9j8xmt/P27_103.pkl?dl=0

**Comment by escorciav** [comment]
Awesome. Thanks a lot!

**Comment by escorciav** [comment]
Is [this commit on the object-mask repo](https://github.com/epic-kitchens/epic-kitchens-100-object-masks/commit/528281d640e51c1ec4077c35dac5a6f4580a4f3d) the corresponding patch for that data?

**Comment by escorciav** [comment]
Great, closing the issue as you addressed my request and I just noticed that you also update the README 😉

**Comment by dmoltisanti** [comment]
FYI, I just updated the [downloader script](https://github.com/epic-kitchens/epic-kitchens-download-scripts/) so that the new correct pickles get downloaded from now on :+1:
