### ISSUE TITLE
Objects class

### ISSUE THREAD

**Issue by amirbar** [epic-kitchens/epic-kitchens-100-hand-object-bboxes#6]
Hi,

Thank you so much for publishing the dataset, annotations, and code. While looking at the bounding box annotations, I noticed that there is no class index attached to each object. Is this information published as well? Also, there are nouns per action published in the csv, should these annotations match up with the actual bounding boxes..?

Thanks again,
Amir

**Comment by escorciav** [comment]
Check the details in the paper reference in the intro. These are predictions of that paper. Thus, unlinked to NOUNs of Epic-Kitchens afaik.

**Comment by dimadamen** [comment]
The hand-object bounding boxes is based on the paper that detects active objects without specifying the class. Please look at the relevant README (paper from University of Michigan)
