### ISSUE TITLE
Scale and aspect ratio of predictions

### ISSUE THREAD

**Issue by escorciav** [epic-kitchens/epic-kitchens-100-hand-object-bboxes#8]
Dear team,

Kindly confirm the scale and aspect ratio of the boxes as they appear to be normalized.

It seems that one must use the [original frame size of the images](https://github.com/epic-kitchens/epic-kitchens-100-hand-object-bboxes/blob/4a25baca01059228b8ac10e7246dc5326a6598b4/src/public_lib/epic_kitchens/hoa/visualisation.py#L86-L88) provided in the epic-100 tar file.

Thanks!
Victor

**Comment by willprice** [comment]
That's right, they're normalised and you have to rescale according to the original images. See https://github.com/epic-kitchens/epic-kitchens-100-hand-object-bboxes/blob/master/notebooks/demo.ipynb and look at the code for DetectionRenderer

**Comment by escorciav** [comment]
Thanks! I took a look at that, but I got confused as I'm not familiar with the abstractions (classes).

I do like it as it makes the code clean and tidy overall. It's just that it increases the slope of the adoption/learning curve :)

**Comment by escorciav** [comment]
@willprice actually the abstractions aren't hard to understand and make the life so easy. Thanks!
