### ISSUE TITLE
Frame number indexing convention

### ISSUE THREAD

**Issue by escorciav** [epic-kitchens/epic-kitchens-100-hand-object-bboxes#9]
Dear Will,

Do you remember our conversation about 1 vs 0-indexed frames?
I will link the issue later.

It seems that the convention is 1-indexed for the hand object detections. Highly appreciate it if you can confirm that 😊 .

```
frame_dir = ...
data_hod_dir = ...
record = ...

...

from epic_kitchens.hoa import load_detections
data_dir = Path(data_hod_dir)
person_id = record.metadata['participant_id']
video_id = record.metadata['video_id']
filename = frame_dir.joinpath(person_id, 'hand-objects', video_id + '.pkl')
video_detections = load_detections(filename)
print(video_detections[0].frame_number)
```

It returns, `1`

Cheers!

**Comment by willprice** [comment]
Hi Victor, they are indeed 1-indexed and correspond to the parsed filenames of the extracted frames.
